server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/kyc_db
    username: kyc_user
    password: kyc_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  service-url: http://localhost:9001